version: "2"
services:
  postgresql-openxds:
    container_name: postgresql-openxds
    image: uwitech/postgresql
    ports:
      - 5432:5432
    volumes:
      - openxds-pgdata:/var/lib/postgresql/data

  openxds:
    container_name: openxds
    image: uwitech/openxds
    ports:
      - "8010:8010"
      - "8020:8020"
    depends_on:
      - postgresql-openxds

volumes:
  openxds-pgdata:
